name: releaseyourblocks.com
favicon: null
layout_spectrum: 0.92635
typography_spectrum: 0.30622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7b6bb'
    - '#63787d'
    - '#232b2d'
    - '#c8828a'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.19909129571169615
purpose: []
