name: releaseyourblocks
favicon: null
layout_spectrum: 0.21226
typography_spectrum: 0.59349
title: releaseyourblocks.com
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171a3d'
    - '#ecbf6a'
    - '#716f7d'
    - '#831337'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
