name: releaseyourblocks.com
favicon: null
layout_spectrum: 0.44995
typography_spectrum: 0.70969
title: releaseyourblocks.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7dcdf'
    - '#1e2e2e'
    - '#83a2b4'
    - '#58767f'
    - '#a2784d'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
