color:
  brandStrength: 0.2
  saturation: 0.4872341
  brandColors:
    - '#d7dcdf'
    - '#1e2e2e'
    - '#83a2b4'
    - '#58767f'
    - '#a2784d'
  lightness: 0.1595745
  rhythmicContrast: 0.4723404
title: releaseyourblocks.com
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  bucket: null
  version: null
  domain: null
favicon: null
layout_spectrum: 0.5340425
purpose: []
name: releaseyourblocks.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.04893617
