name: releaseyourblocks.com
favicon: null
layout_spectrum: 0.44995
typography_spectrum: 0.70969
title: releaseyourblocks.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0793d7'
    - '#c9e3ef'
    - '#0d0a04'
    - '#6e5573'
    - '#fd7b2e'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
