name: releaseyourblocks
favicon: null
layout_spectrum: 0.56127
typography_spectrum: 0.59349
title: releaseyourblocks.com
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99d1e0'
    - '#231f20'
    - '#719eb1'
    - '#49666e'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
