title: RYB
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6875
  brandStrength: 0.375
  rhythmicContrast: 0.5
  brandColors:
    - '#0793d7'
    - '#c9e3ef'
    - '#0d0a04'
    - '#6e5573'
    - '#fd7b2e'
  lightness: 0.5625
cta:
  version: null
  bucket: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: releaseyourblocks.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.97949
layout_spectrum: 0.9747049
