name: releaseyourblocks
favicon: null
layout_spectrum: 0.5340425
typography_spectrum: 0.04893617
title: releaseyourblocks.com
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7dcdf'
    - '#1e2e2e'
    - '#83a2b4'
    - '#58767f'
    - '#a2784d'
  brandStrength: 0.2
  lightness: 0.1595745
  saturation: 0.4872341
  rhythmicContrast: 0.4723404
purpose: []
